### ISSUE TITLE
Clarify relationship to original project

### ISSUE THREAD

**Issue by sfiera** [akuker/RASCSI#13]
The [README](https://github.com/akuker/RASCSI/blob/master/README.md) says:
> For convenience this is a dump of the RASCSI archive RaSCSI version 1.47 available at: http://retropc.net/gimons/rascsi/

It’s not just a mirror anymore. Is there any hope to merge improvements from GIMONS RaSCSI into akuker/RaSCSI or vice versa, or are the two effectively different projects with the same name now?

**Comment by akuker** [comment]
I've been watching GIMONS' project for updates, but haven't seen any since April. 

This project is a fork of GIMONS' project. He has the code available on his web page, but doesn't have a github repo or anything like that to allow community submissions. (I sent him a bug fix for 1.47, but doesn't look like he's pulled it into his page)

I also translated the entire project into English, so, IMO they're two different projects that are compatible with each other. I have a lot of planned updates to the code that will make it even more different, beyond just the English vs Japanese. 

GIMONS is also targeting a completely different hardware architecture, the Sharp X68000. I don't have one of these, and have no way to see if my changes are still compatible. 

Good suggestion though! I'll try to summarize these ramblings in the README
