### ISSUE TITLE
Discard current baremetal support

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#139]
@akuker Correct me if I am wrong: You indicated that you are not interested in baremetal support as it is right now, but favor a different solution. In this case the existing code would profit from all those baremetal ifdefs to be removed. This would definitely improve code maintainability.

**Comment by akuker** [comment]
Agreed. Let's just make that executive decision now.... Baremetal support can be removed.

If someone really needs baremetal support, they can go with the GIMONS version of the code.

*Maybe* someday we add it back in... but even then I would probably use a FreeRTOS or something instead of just bare metal.

**Comment by uweseimet** [comment]
Cool! I will address this issue next, because any other changes will profit from the code having been cleaned up first.

**Comment by uweseimet** [comment]
Resolved with https://github.com/akuker/RASCSI/commit/3c5a0003a43fd3efd16c14e23918e8865a4f77cc
