### ISSUE TITLE
Update the web interface to prohibit "bad" operations

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#25]
Currently, through the web interface, the user can delete images that might currently be mounted by the rascsi service. The UI should be updated to disable/hide the delete button for images that are currently mounted.

Additionally, if issue #23 is implemented, the user shouldn't be able to download mounted images either, since they could be in a partially-written state.

**Comment by rdmark** [comment]
![imagedelete](https://user-images.githubusercontent.com/2108467/133892322-65d20f60-4f9d-4fa1-bad5-9564f6c6a1b0.png)

This is being fixed with https://github.com/akuker/RASCSI/pull/242 with file creation/deletion being moved to rascsi backend, and the web ui using protobuf commands for these operations.
