### ISSUE TITLE
Set up Coverity Analysis of the code

### ISSUE THREAD

**Issue by akuker** [akuker/RASCSI#28]
Coverity static analysis software is an industry leading tool that is available for free to open source projects. It would help improve the quality of the code if we were to run this analysis on RaSCSI.

**Comment by akuker** [comment]
I started setting up the project, but didn't get very far...
https://scan.coverity.com/projects/akuker-rascsi?tab=overview

**Comment by uweseimet** [comment]
@akuker Any news on this? Not having automated builds of the develop and feature branches (in order to also have automated unit tests) and not having any code analysis, e.g. based on SonarQube, which is free for C++ for non-commercial projects (https://sonarcloud.io/explore/projects) is quite a problem. The more code is added without automated testing, the more likely regressions get.

**Comment by akuker** [comment]
Agreed. Its all a matter of priority. This isn't an especially "sexy" feature to work on, so its easy to push it down the priority list. I definitely have not forgotten about it.

**Comment by uweseimet** [comment]
@akuker Yes, just like documentation tickets like this are not that popular. But the more code we have, the more important this ticket gets.
My experience from previous projects is that having code analysis and working steadily on improving code metrics helps preventing a lot of issues. And it uncovers a lot of issues, which would otherwise have taken a lot of time in debugging the problems they would have caused.

**Comment by rdmark** [comment]
@akuker What did you get stuck on setting up the Coverity project? I can see that you got it to scan a whole bunch of code, so you must have made some progress!

**Comment by uweseimet** [comment]
@akuker @rdmark I think I have resolved this ticket, please see https://github.com/akuker/RASCSI/pull/806.

**Comment by rdmark** [comment]
Coverity is very similar to SonarQube in its capabilities, I believe.

**Comment by akuker** [comment]
Coverity looks like it is similar to SonarQube (from my 30 second google search of SonarQube). Coverity can identify dead code, but that's not its primary function. Its more like lint on steroids.

I'm excited to see gcov being used. As for this ticket, I don't care. We can close it, we can leave it open. Whatever.

There are other priorities... I'll just close it.
