### ISSUE TITLE
oled monitor - start.sh logic assumption

### ISSUE THREAD

**Issue by hsiboy** [akuker/RASCSI#388]
# Info

- Which version of Pi are you using: Pi 4
- Which github revision of software: origin/develop 
- Which board version: fullspec
- Which computer is the RaSCSI connected to: Roland W30 (sampling workstation)

# Describe the issue

The file `start.sh` in `/src/oled_monitor/` makes a test to see if `venv/` exists, if it does  it calls `source venv/bin/activate` However, the same script also checks to see if it is running the latest version or not.
Because i'm running from develop and trying to keep up with the changes @rdmark is making, i had a dirty directory, but i was up to date. `venv/` existed, but was in a corrupt state. The script fails after the test for the existence of `venv` because an assumption is made. 
I suggest that if an update occurs, `venv/` be removed and a fresh one created.

Also, because this was an in place upgrade, there was already a `rascsi_oled_monitor.py` running, which was installed by `easyinstall.sh`.  Should there be a test for a running `rascsi_oled_monitor.py` which may have been previously installed by `easyinstall.sh`?

**Comment by rdmark** [comment]
This PR contains code for capturing two known bad venv states: When source fails due to a missing (or with bad permissions) activate script, and when pip fails due to general corruption or mismatched version in venv. I ran into the latter issue when upgrading from Buster to Bullseye.

https://github.com/akuker/RASCSI/pull/510
