### ISSUE TITLE
Get supported device types from rascsi rather than hard coded help text

### ISSUE THREAD

**Issue by rdmark** [akuker/RASCSI#602]
The web interface currently has hard coded help text under Image File Management for mapping device type acronyms to human readable device names. Ideally, this should be provided by the rascsi backend instead, to avoid f.e. playing catch-up when rascsi capabilities change.

**Comment by rdmark** [comment]
@uweseimet What do you say about introducing something like an enum PbDeviceName with human readable device type names, which is then exposed through the PbDeviceTypeProperties message?

**Comment by uweseimet** [comment]
@rdmark Device type names are a matter of localization and of what a client wants to use as a name. Adding localization information to the protobuf interface would not be a good idea, because this is a technical interface. A client can map the PbDeviceType enum values to the translations it needs.

**Comment by rdmark** [comment]
@uweseimet Doesn't this mean that each client will have to maintain their own set of canonical device names, that may then diverge between clients? I was just hoping that since supported devices are constant as far as the clients are concerned, that the rascsi backend would be responsible for the canonical human-readable names.

**Comment by uweseimet** [comment]
@rdmark Yes, each client is responsible for localizing most of its UI, and the strings used for localization in different clients can diverge in any case. That's the way it is, not just with RaSCSI ;-). Country or language specific data are never part of an interface, and I doubt that you will find any interface that handles this differently.

**Comment by uweseimet** [comment]
@rdmark Can it be that your suggestion would fail, not because of (as I tried to point out) wrong use of interfaces, but because you cannot have any human readable string based on enums in an interface definition? You would at least have to escape special characters which are not allowed in enums, like blanks or umlauts. In addition, enum values are by convention upper case, so you would have to set up rules on how to deal with upper and lower case. There are probably more issues of that kind, which besides the technical implications show that interfaces are not meant to deal with localization.

**Comment by rdmark** [comment]
Implementation for the Web UI: https://github.com/akuker/RASCSI/pull/655
