### ISSUE TITLE
Use C++ filesystem library/iostreams for file operations

### ISSUE THREAD

**Issue by uweseimet** [akuker/RASCSI#911]
Instead of the low-level C API the C++ filesystem library and C++ iostreams shall be used for image file operations (protobuf interface) and other file-based operations. This will result in more portable and more transparent code with better error handling.

**Comment by akuker** [comment]
As a request - however this is implemented, I'd like to have a path to support FreeRTOS (or something similar) file system APIs. I think there is an opportunity to run RaSCSI on FreeRTOS.

Would you consider keeping this as a separate layer (rather than calling the C++ FS APIs directly) so that we can swap OS's in the future?

**Comment by uweseimet** [comment]
@akuker Can you please make this a separate ticket? I have alaready completed the changes and unit tests required for this ticket.

**Comment by akuker** [comment]
I'm fine doing it under a different ticket, since you've got the changes already done. I'm sure there will be other changes to port to FreeRTOS, so we can cross that bridge when we get there.
